[package]
name = "hydrogen"
version = "0.0.1-alpha.9"
authors = ["Nashira Deer <nashiradeer@gmail.com>"]
edition = "2021"
description = "Discord music bot powered by Lavalink and focusing on performance, features, usability and practicality."
readme = "README.md"
keywords = ["discord", "lavalink", "music"]
publish = false

[features]
default = ["builtin-language"]
# Enable the builtin default language. (default)
# Don't disable if you will build using the provided Dockerfile because the image willn't include the 'en-US' language file.
builtin-language = []

[dependencies]
async-trait = "0.1.83"
dashmap = "6.1.0"
futures = "0.3.28"
rand = "0.8.5"
regex = "1.10.6"
serde_json = "1.0.128"
tokio-native-tls = "0.3.1"
toml = "0.8.19"
tracing = "0.1.37"

[dependencies.async-tungstenite]
package = "async-tungstenite"
version = "0.28.0"
features = ["tokio-runtime", "tokio-native-tls"]

[dependencies.clap]
version = "4.5.18"
features = ["derive"]

[dependencies.hydrogen-i18n]
package = "hydrogen-i18n"
version = "2.2.0"
default-features = false
features = ["serenity"]

[dependencies.reqwest]
package = "reqwest"
version = "0.12.7"
default-features = false
features = ["native-tls", "json"]

[dependencies.serde]
package = "serde"
version = "1.0.210"
features = ["derive"]

[dependencies.serenity]
package = "serenity"
version = "0.12.2"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "voice",
    "native_tls_backend",
]

[dependencies.songbird]
package = "songbird"
version = "0.4.3"
default-features = false
features = ["gateway", "serenity", "native"]

[dependencies.tokio]
package = "tokio"
version = "1.40.0"
features = ["macros", "rt-multi-thread"]

[dependencies.tracing-subscriber]
package = "tracing-subscriber"
version = "0.3.17"
features = ["env-filter"]
