FROM rust:1.84.0-slim-bookworm AS builder
RUN apt-get update -y && apt-get upgrade -y
WORKDIR /app
COPY src/ src/
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
RUN cargo build -r

FROM debian:bookworm-slim
RUN apt update -y && apt upgrade -y
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
CMD ["/app/hydrogen"]