FROM rust:1.85.0-alpine3.21 AS builder
RUN apk -U upgrade
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY . .
RUN cargo build --release --package hydrogen --no-default-features --features simd-json,rustls-tls

FROM gcr.io/distroless/static-debian12:latest
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
CMD ["/app/hydrogen"]