FROM rust:1.85.0-slim-bookworm AS builder
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y libssl-dev pkg-config
WORKDIR /app
COPY . .
RUN cargo build --release --package hydrogen --no-default-features --features simd-json,native-tls

FROM debian:bookworm-20250224-slim
RUN apt update -y && apt upgrade -y
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
CMD ["/app/hydrogen"]