FROM rust:1.81.0-alpine3.20 AS builder
RUN apk -U upgrade
RUN apk add libc-dev openssl-dev openssl-libs-static
WORKDIR /app
COPY langs/ langs/
COPY src/ src/
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
RUN cargo build -r
RUN rm langs/en-US.json

FROM alpine:3.20.0
RUN apk -U upgrade
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
COPY --from=builder /app/langs langs/
ENV RUST_LOG=hydrogen=info
ENV HYDROGEN_LANGUAGE_PATH=/app/langs
CMD ["/app/hydrogen"]