FROM rust:1.85.0-alpine3.21 AS builder
RUN apk -U upgrade
RUN apk add --no-cache musl-dev pkgconfig openssl-dev openssl-libs-static 
WORKDIR /app
COPY . .
RUN cargo build --release --package hydrogen --no-default-features --features simd-json,native-tls

FROM alpine:3.21.3
RUN apk -U upgrade
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
CMD ["/app/hydrogen"]