FROM rust:1.84.1-alpine3.21 AS builder
RUN apk -U upgrade
RUN apk add --no-cache musl-dev
WORKDIR /app
COPY src/ src/
COPY Cargo.toml Cargo.toml
COPY Cargo.lock Cargo.lock
RUN cargo build -r

FROM alpine:3.21.2
RUN apk -U upgrade
WORKDIR /app
COPY --from=builder /app/target/release/hydrogen hydrogen
CMD ["/app/hydrogen"]